//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieRequest
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public bool Play { get; set; }
        public Nullable<System.DateTime> Processed { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
